### ISSUE TITLE
Failed to convert Greenfield v0.5.1 world

### ISSUE THREAD

**Issue by Foghrye4** [OpenCubicChunks/CubicChunksConverter#2]
In attempt to use converter on Greenfield v0.5.1 world I've got such output:
```
Exception in thread "Chunk and File counting thread" java.lang.IllegalArgumentException: Invalid name r.76.0.mcr
	at cubicchunks.regionlib.impl.MinecraftChunkLocation.fromRelative(MinecraftChunkLocation.java:102)
	at cubicchunks.converter.lib.AnvilToCubicChunksConverter.lambda$null$6(AnvilToCubicChunksConverter.java:539)
	at cubicchunks.regionlib.region.provider.SimpleRegionProvider.forAllRegions(SimpleRegionProvider.java:106)
	at cubicchunks.regionlib.region.provider.CachedRegionProvider.forAllRegions(CachedRegionProvider.java:119)
	at cubicchunks.regionlib.SaveSection.forAllRegions(SaveSection.java:85)
	at cubicchunks.converter.lib.AnvilToCubicChunksConverter.lambda$startCounting$7(AnvilToCubicChunksConverter.java:536)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by Niko-sk2x** [comment]
You are trying to convert world that has been converted from pre-MC1.2, and it still contains old .mcr files, delete those. This doesn't make this non-issue on my side, I should just ignore those, but you can work around it.
